[project]
name = "crud-task"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "coreapi>=2.3.3",
    "django>=5.1.6",
    "django-cors-headers>=4.7.0",
    "djangorestframework>=3.15.2",
    "setuptools>=75.8.2",
]